Спринт 13. Домашнее задание "ShareIt".
Latarho/java-shareit pull request #2
Opened 2022-08-14 19:01 UTC by Latarho

2022-08-16 07:44 UTC, alexache requested changes
Комментарии по коду

2022-08-16 07:44 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +}
Мне кажется, тут еще не хватает requestId

2022-08-16 07:44 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        return ItemMapper.toItemDto(itemStorage.create(newItem));
Тут можно было бы только обновить поле id у ItemDto объекта, чтобы не пересоздавать его

2022-08-16 07:44 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        List<ItemDto> itemsDtoWithOwner = new ArrayList<>();
Можно было бы и использовать Stream API здесь и написать одной строкой что-то вроде return itemsWithOwner.stream().map(ItemMapper::toItemDto).collect(Collectors.toList());

2022-08-16 07:44 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            throw new ResponseStatusException(HttpStatus.FORBIDDEN,
Обычно стараются не смешивать в разных частях кода Exception и то, на какой HTTP код он маппится - создают разные виды эксепшенов и пишут ControllerAdvice (как в прошлом проекте), это позволяет не завязываться в сервисах на то, что возвращается клиенту. Контроллеры могут быть разными в теории

2022-08-16 07:44 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +
Какие-то лишние переносы

2022-08-16 07:44 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        newItem.setOwner(userStorage.getById(ownerId));
Получается, что userStorage.getById() вызывается несколько раз - один  раз в checkUser, другой здесь, можно было бы обойтись одним вызовом

2022-08-16 07:44 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        List<ItemDto> foundItemsDto = new ArrayList<>();
Тут тоже можно использовать стримы

2022-08-16 07:44 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +            request = request.toLowerCase();
Может вынести эту переменную до цикла, чтобы не делать это дейстаие на каждый шаг цикла?

2022-08-16 07:44 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            if (item.getAvailable()) {
Эту проверку можно вынести еще в сторадж, чтобы использовать меньше данных

2022-08-16 07:44 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/storage/UserStorage.java
> +    User update(User user);
Объект юзера никак не меняется, его можно не возвращать

2022-08-17 09:49 UTC, Latarho commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +}
Добавил.

2022-08-17 10:26 UTC, Latarho commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        List<ItemDto> itemsDtoWithOwner = new ArrayList<>();
Переделал в функциональном стиле.

2022-08-17 10:26 UTC, Latarho commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        List<ItemDto> foundItemsDto = new ArrayList<>();
Переделал в функциональном стиле.

2022-08-17 10:27 UTC, Latarho commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            if (item.getAvailable()) {
Сделал через фильтр, но в сервисе.

2022-08-17 12:03 UTC, Latarho commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +            request = request.toLowerCase();
Вынес до цикла.

2022-08-17 12:11 UTC, Latarho commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +
Исправил.

2022-08-17 12:24 UTC, Latarho commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        newItem.setOwner(userStorage.getById(ownerId));
Исправлено.

2022-08-17 13:17 UTC, Latarho commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            throw new ResponseStatusException(HttpStatus.FORBIDDEN,
Принял к сведению.

2022-08-17 13:17 UTC, Latarho commented on src/main/java/ru/practicum/shareit/user/storage/UserStorage.java
> +    User update(User user);
Принял к сведению.

2022-08-17 21:30 UTC, alexache approved these changes
Основные комментарии учтены

2022-08-29 18:07 UTC, merged