Спринт 14. Домашнее задание "ShareIt".
Latarho/java-shareit pull request #3
Opened 2022-09-03 17:45 UTC by Latarho

2022-09-05 08:21 UTC, alexache requested changes
Комментарии по функциональному стилю опциональные, а вот переиспользование результата запроса очень желательно

2022-09-05 08:21 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/model/State.java
> +    UNSUPPORTED_STATUS
А должен ли быть такой стейт?

2022-09-05 08:21 UTC, alexache commented on src/main/resources/application.properties
> +#spring.datasource.driverClassName=org.postgresql.Driver
В итоге сейчас используется H2, а не PostgreSQL?

2022-09-05 08:21 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        if (userId == null) {
Насколько я помню, это лишняя проверка, если в запросе не будет этого хедера, то сам спринг вернет 400 ошибку без попадания в метод контроллера

2022-09-05 08:21 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (userRepository.findById(userId).isEmpty()) {
или в функциональном стиле userRepository.findById(userId).orElseThrow(() -> new UserNotFoundException(..))

2022-09-05 08:21 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            if (itemRepository.findById(booking.getItem().getId()).isEmpty()) {
Тоже можно сделать в функциональном стиле, чтобы было поменьше вложенности if-else

2022-09-05 08:21 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                    if (!itemRepository.findById(booking.getItem().getId()).orElseThrow().getAvailable()) {
Это уже второй запрос, а ниже еще третий и четвертый запрос получения вещь по айди, имеет смысл сохранить результат в переменной, чтобы не делать столько лишних запросов

2022-09-05 08:21 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                            booking.setBooker(userRepository.findById(userId).get());
А это второй запрос получения юзера по айди, значит тоже стоит завести переменную

2022-09-05 08:21 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            if (bookingRepository.findById(bookingId).isEmpty()) {
Стоит завести переменную для хранения бронирования по айди, ниже есть еще несколько таких же запросов

2022-09-05 08:21 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                    throw new ItemNotBelongsToUserException("Вещь недоступна для бронирования для пользователя id: "
Текст ошибки немного не сходится с сутью ошибки, здесь вед ьпро то, что только владелец вещи может подтвердждать бронирование?

2022-09-05 08:21 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            List<BookingDto> listBookingDto = new ArrayList<>();
Можно переделать в функциональном стиле с .stream.map(BookingMapper::toBookingDto).collect(..)

2022-09-05 08:57 UTC, Latarho commented on src/main/resources/application.properties
> +#spring.datasource.driverClassName=org.postgresql.Driver
От наставника был такой комментарий:
![image](https://user-images.githubusercontent.com/53216025/188410229-0db7c66c-aabc-421c-a16a-776fe264f300.png)

2022-09-05 20:15 UTC, Latarho commented on src/main/java/ru/practicum/shareit/booking/model/State.java
> +    UNSUPPORTED_STATUS
Исправлено, enum удалил.

2022-09-05 20:20 UTC, Latarho commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        if (userId == null) {
Исправлено.

2022-09-05 20:28 UTC, Latarho commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                    if (!itemRepository.findById(booking.getItem().getId()).orElseThrow().getAvailable()) {
Исправлено.

2022-09-05 20:28 UTC, Latarho commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                            booking.setBooker(userRepository.findById(userId).get());
Исправлено.

2022-09-05 20:34 UTC, Latarho commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            if (bookingRepository.findById(bookingId).isEmpty()) {
Исправлено.

2022-09-05 20:46 UTC, Latarho commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                    throw new ItemNotBelongsToUserException("Вещь недоступна для бронирования для пользователя id: "
Исправлено.

2022-09-06 08:56 UTC, alexache approved these changes

2022-09-06 08:56 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                case ("ALL"):
Удалить енам - это кардинально, лучше бы его вернуть обратно :) 
Что можно сделать по-другому - получать строку на вход контроллера, как теперь, и делать State.valueOf(state) с отловом IllegalArgumentException

2022-09-10 17:19 UTC, merged