Спринт 15. Домашнее задание "ShareIt".
Latarho/java-shareit pull request #4
Opened 2022-09-15 20:17 UTC by Latarho

Тесты для BookingController, ItemController, BookingServiceImpl помечены TODO и будут реализованы после проверки. Тесты на другие классы готовы к проверке.

2022-09-16 20:56 UTC, alexache requested changes
Нужно доделывать тесты по списку: не хватает тестов  контроллеров с ТуДу, тестов JPA на UserRepository, юнит тестов на каждого маппера, а также не вижу  ни одного интеграционного тестов

2022-09-16 20:56 UTC, alexache commented on src/main/java/ru/practicum/shareit/requests/dto/ItemRequestCreatingDto.java
> +public class ItemRequestCreatingDto {
Мне кажется, можно было бы обойтись одним ItermRequestDto с проставлением таймстемпа и необязательным id на входе

2022-09-16 20:56 UTC, alexache commented on src/main/java/ru/practicum/shareit/requests/service/ItemRequestService.java
> +    // Создание запроса на вещь
Комментарии в интерфейсе - это прекрасно. 
В идеале лучше придерживаться JavaDoc  формата (это не обязательно делать в рамках данного задания, просто комментарий на будущее)

2022-09-16 20:56 UTC, alexache commented on src/main/java/ru/practicum/shareit/requests/service/ItemRequestServiceImpl.java
> +            itemRequest.setRequesterId(userId);
Эти 2 поля тоже можно было бы передать в вызов метода маппера

2022-09-16 20:56 UTC, alexache commented on src/main/java/ru/practicum/shareit/requests/model/ItemRequest.java
> +    @Column(name = "requester_id", nullable = false)
Можно бы хранить объект юзера и с помощью аннотаций JoinColumn

2022-09-16 20:56 UTC, alexache commented on src/main/java/ru/practicum/shareit/requests/service/ItemRequestServiceImpl.java
> +                ItemRequestWithItemsDto itemFound = getById(itemRequest.getId(), userId);
Можно сделать немного оптимальнее и получать сразу список Item по requestId с помощью SQL конструкции в духе where request_id in .. , то есть передавая весь список реквестов вместо прохождения по циклу

2022-09-16 20:56 UTC, alexache commented on src/main/java/ru/practicum/shareit/requests/service/ItemRequestServiceImpl.java
> +            if (itemRequestRepository.findById(requestId).isEmpty()) {
itemRequestRepository.findById(requestId) вызывается дважды

2022-09-16 20:56 UTC, alexache commented on src/main/java/ru/practicum/shareit/requests/service/ItemRequestServiceImpl.java
> +            ItemRequestWithItemsDto itemFound = getById(itemRequest.getId(), userId);
Это тоже лучше сделать одним запросо к БД, а не множеством в цикле

2022-09-16 20:56 UTC, alexache commented on src/test/java/ru/practicum/shareit/controller/ItemRequestControllerTest.java
> +package ru.practicum.shareit.controller;
Больше принято, что тест находится в таком же пакете, как и тестируемый класс/сущность, то есть пакеты не по типам тестов, а по сущностям

2022-09-16 20:56 UTC, alexache commented on src/test/java/ru/practicum/shareit/controller/ItemRequestControllerTest.java
> +                        is((itemRequestDto.getCreated().toString()).replaceAll("0+$", ""))));
Хорошо бы еще добавить verify на то, что метод сервиса вызывался

2022-09-16 20:56 UTC, alexache commented on src/test/java/ru/practicum/shareit/controller/ItemRequestControllerTest.java
> +    }
Не хватает теста на метод контроллера с пагинацией /requests/all

2022-09-16 20:56 UTC, alexache commented on src/test/java/ru/practicum/shareit/controller/UserControllerTest.java
> +    UserDto userDto;
Модификатор доступа

2022-09-16 20:56 UTC, alexache commented on src/test/java/ru/practicum/shareit/controller/UserControllerTest.java
> +    void checkDeleteUser() throws Exception {
Название метода не соотноситься с кодом теста. здесь ведь не вызывается метод удаления?

2022-09-16 20:56 UTC, alexache commented on src/test/java/ru/practicum/shareit/controller/UserControllerTest.java
> +                .andExpect(jsonPath("$.email", is(userDto.getEmail())));
Здесь тоже в конце тест методов не помешает использования метода  verify на то, что методы сервиса вызывались

2022-09-16 20:56 UTC, alexache commented on src/test/java/ru/practicum/shareit/jpa/BookingRepositoryTest.java
> +    User userOwner;
Модификаторы дл=оступа у полей нужны

2022-09-16 20:56 UTC, alexache commented on src/test/java/ru/practicum/shareit/jpa/BookingRepositoryTest.java
> +    Booking BookingOne;
Названия переменных не должны быть с заглавной буквы

2022-09-16 20:56 UTC, alexache commented on src/test/java/ru/practicum/shareit/jpa/BookingRepositoryTest.java
> +        List<Booking> listToCompare = new ArrayList<>();
Можно писать List.of(bookingOne, bookingTwo)

2022-09-16 20:56 UTC, alexache commented on src/test/java/ru/practicum/shareit/jpa/ItemRepositoryTest.java
> +    User userOwnerOne;
Модификаторы доступа

2022-09-16 20:56 UTC, alexache commented on src/test/java/ru/practicum/shareit/jpa/ItemRepositoryTest.java
> +        List<Item> foundItems = itemRepository.search("Это вещь номер од", PageRequest.of(0, 5));
Хорошо бы еще тест поиска, который сработает по описанию вещи, а не названию

2022-09-16 20:56 UTC, alexache commented on src/test/java/ru/practicum/shareit/jpa/ItemRequestRepositoryTest.java
> +    User userRequesterOne;
Модификаторы доступа

2022-09-16 20:56 UTC, alexache commented on src/test/java/ru/practicum/shareit/jpa/BookingRepositoryTest.java
> +                PageRequest.of(0, 5));
Есть Pageable.unpaged(), подходящий под тесты

2022-09-16 20:56 UTC, alexache commented on src/test/java/ru/practicum/shareit/unit/service/ItemRequestServiceImplTest.java
> +    UserRepository userRepository;
Модификаторы доступа

2022-09-17 07:41 UTC, Latarho commented on src/main/java/ru/practicum/shareit/requests/service/ItemRequestService.java
> +    // Создание запроса на вещь
Сделаю в след. спринте во всем проекте в формате JavaDoc.

2022-09-17 08:10 UTC, Latarho commented on src/main/java/ru/practicum/shareit/requests/model/ItemRequest.java
> +    @Column(name = "requester_id", nullable = false)
Исправлено.

2022-09-17 08:23 UTC, Latarho commented on src/main/java/ru/practicum/shareit/requests/service/ItemRequestServiceImpl.java
> +            if (itemRequestRepository.findById(requestId).isEmpty()) {
Исправлено.

2022-09-17 08:46 UTC, Latarho commented on src/test/java/ru/practicum/shareit/unit/service/ItemRequestServiceImplTest.java
> +    UserRepository userRepository;
Исправлено.

2022-09-17 09:01 UTC, Latarho commented on src/test/java/ru/practicum/shareit/jpa/BookingRepositoryTest.java
> +                PageRequest.of(0, 5));
Исправлено. Однако, в чем профит? тесты атомарные, независимые.

2022-09-17 09:04 UTC, Latarho commented on src/test/java/ru/practicum/shareit/jpa/ItemRequestRepositoryTest.java
> +    User userRequesterOne;
Исправлено.

2022-09-17 09:08 UTC, Latarho commented on src/test/java/ru/practicum/shareit/jpa/ItemRepositoryTest.java
> +        List<Item> foundItems = itemRepository.search("Это вещь номер од", PageRequest.of(0, 5));
Тест добавил.

2022-09-17 09:08 UTC, Latarho commented on src/test/java/ru/practicum/shareit/jpa/ItemRepositoryTest.java
> +    User userOwnerOne;
Исправлено.

2022-09-17 11:45 UTC, Latarho commented on src/test/java/ru/practicum/shareit/jpa/BookingRepositoryTest.java
> +        List<Booking> listToCompare = new ArrayList<>();
Исправлено везде.

2022-09-17 11:45 UTC, Latarho commented on src/test/java/ru/practicum/shareit/jpa/BookingRepositoryTest.java
> +    Booking BookingOne;
Исправлено везде.

2022-09-17 11:46 UTC, Latarho commented on src/test/java/ru/practicum/shareit/jpa/BookingRepositoryTest.java
> +    User userOwner;
Исправлено.

2022-09-17 12:47 UTC, Latarho commented on src/test/java/ru/practicum/shareit/controller/UserControllerTest.java
> +    UserDto userDto;
Исправлено.

2022-09-17 12:48 UTC, Latarho commented on src/test/java/ru/practicum/shareit/controller/UserControllerTest.java
> +                .andExpect(jsonPath("$.email", is(userDto.getEmail())));
Не понимаю что здесь нужно сделать.

2022-09-17 12:56 UTC, Latarho commented on src/test/java/ru/practicum/shareit/controller/UserControllerTest.java
> +    void checkDeleteUser() throws Exception {
Исправлено.

2022-09-17 12:59 UTC, Latarho commented on src/test/java/ru/practicum/shareit/controller/ItemRequestControllerTest.java
> +                        is((itemRequestDto.getCreated().toString()).replaceAll("0+$", ""))));
Не понимаю что здесь нужно сделать.

2022-09-17 13:11 UTC, Latarho commented
> 
Юниты на UserRepository не требуются.
![image](https://user-images.githubusercontent.com/53216025/190858690-ad1c799c-e413-4e5d-b2ce-e8ad45df95fd.png)

2022-09-18 12:58 UTC, Latarho commented on src/main/java/ru/practicum/shareit/requests/dto/ItemRequestCreatingDto.java
> +public class ItemRequestCreatingDto {
Исправлено.

2022-09-18 12:59 UTC, Latarho commented on src/main/java/ru/practicum/shareit/requests/service/ItemRequestServiceImpl.java
> +            itemRequest.setRequesterId(userId);
Исправлено.

2022-09-18 12:59 UTC, Latarho commented on src/main/java/ru/practicum/shareit/requests/service/ItemRequestServiceImpl.java
> +                ItemRequestWithItemsDto itemFound = getById(itemRequest.getId(), userId);
Исправлено.

2022-09-18 12:59 UTC, Latarho commented on src/main/java/ru/practicum/shareit/requests/service/ItemRequestServiceImpl.java
> +            ItemRequestWithItemsDto itemFound = getById(itemRequest.getId(), userId);
Исправлено.

2022-09-18 12:59 UTC, Latarho commented on src/test/java/ru/practicum/shareit/controller/ItemRequestControllerTest.java
> +package ru.practicum.shareit.controller;
Структуру изменил.

2022-09-18 19:19 UTC, alexache commented on src/test/java/ru/practicum/shareit/jpa/BookingRepositoryTest.java
> +                PageRequest.of(0, 5));
Не заморачиваться и отлавливать странные баги, которые могут не проявляться, когда страницы захардкожены

2022-09-19 08:03 UTC, alexache approved these changes

2022-09-19 08:03 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +        BookingDto getById(Long userId, Long bookingId) throws ItemNotBelongsToUserException, UserNotFoundException,
Странный отступ появился

2022-09-19 08:03 UTC, alexache commented on src/main/java/ru/practicum/shareit/requests/dto/ItemRequestMapper.java
> +        List<ItemRequestDto> listItemRequestDto = new ArrayList<>();
Отчего здесь не Stream API? :)

2022-09-19 08:03 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    User user;
модификаторы доступа

2022-09-19 08:03 UTC, alexache commented on src/test/java/ru/practicum/shareit/requests/ItemRequestServiceIntegrationTest.java
> +//        itemRequestRepository.saveAndFlush(itemRequest);
Лучше подчищать от комментариев в коде

2022-09-19 12:17 UTC, merged