Спринт 16. Домашнее задание "ShareIt".
Latarho/java-shareit pull request #5
Opened 2022-09-26 20:31 UTC by Latarho

2022-09-29 19:19 UTC, alexache requested changes

2022-09-29 19:19 UTC, alexache commented on gateway/src/main/java/ru/practicum/Main.java
> +        System.out.println("Hello world!");
Для чего этот класс? :)

2022-09-29 19:19 UTC, alexache commented on gateway/src/main/java/ru/practicum/shareit/user/UserController.java
> +    public Object create(@RequestBody @Validated UserDto userDto) {
Куда-то потерялись ResponseEntity по пути от клиента до контроллера

2022-09-29 19:19 UTC, alexache commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +        log.info("Получен запрос - поиск вещи по тексту: " + text);
Можно бы добавить проверку на text, что он не пустой

2022-09-29 19:19 UTC, alexache commented on server/src/main/java/ru/practicum/Main.java
> +    public static void main(String[] args) {
Тоже какой-то лишний класс

2022-09-29 19:19 UTC, alexache commented on server/src/test/java/ru/practicum/shareit/user/UserServiceIntegrationTest.java
> +//    @Test
Если этот тест стал лишним, то его лучше удалить

2022-09-29 19:44 UTC, Latarho commented on gateway/src/main/java/ru/practicum/Main.java
> +        System.out.println("Hello world!");
Удалил... произошло после того как я создал новый module в idea, потом забыл удалить

2022-09-29 19:48 UTC, Latarho commented on gateway/src/main/java/ru/practicum/shareit/user/UserController.java
> +    public Object create(@RequestBody @Validated UserDto userDto) {
Исправлено

2022-09-29 19:49 UTC, Latarho commented on server/src/main/java/ru/practicum/Main.java
> +    public static void main(String[] args) {
Удалил... произошло после того как я создал новый module в idea, потом забыл удалить

2022-09-29 20:56 UTC, Latarho commented on server/src/test/java/ru/practicum/shareit/user/UserServiceIntegrationTest.java
> +//    @Test
Удалил

2022-09-30 08:48 UTC, Latarho commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +        log.info("Получен запрос - поиск вещи по тексту: " + text);
Добавил проверку на уровне controller в модуле gateway

2022-09-30 19:45 UTC, alexache approved these changes

2022-10-01 18:14 UTC, merged